# Generated by Django 5.2.8 on 2025-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dukkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='Dükkan Adı')),
                ('kategori', models.CharField(choices=[('MOTOR', 'Motor ve Mekanik'), ('ELEKTRIK', 'Oto Elektrik ve Beyin'), ('KAPORTA', 'Kaporta ve Boya'), ('LASTIK', 'Lastik ve Jant'), ('YEDEK', 'Yedek Parça'), ('EGZOZ', 'Egzoz ve Emisyon'), ('TORNACI', 'Torna ve Tesviye')], max_length=50, verbose_name='Kategori')),
                ('uzmanlik', models.CharField(max_length=300, verbose_name='Uzmanlık (Örn: Sadece BMW bakar)')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(verbose_name='Açık Adres')),
                ('konum_linki', models.URLField(blank=True, max_length=500, verbose_name='Google Harita Linki')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='dukkanlar/', verbose_name='Dükkan Fotosu')),
                ('onayli_esnaf', models.BooleanField(default=False, verbose_name='Mavi Tik (Güvenilir Esnaf)')),
                ('vitrin_uye', models.BooleanField(default=False, verbose_name='Vitrin Üye (En Üstte Çıkar)')),
            ],
            options={
                'verbose_name_plural': 'Sanayi Esnafları',
            },
        ),
    ]
