# Generated by Django 5.2.8 on 2025-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukkan',
            name='kategori',
            field=models.CharField(choices=[('MOTOR', 'Motor ve Mekanik'), ('BAKIM', 'Periyodik Bakım & Yağ'), ('ELEKTRIK', 'Oto Elektrik ve Beyin'), ('AKU', 'Akü Satış & Değişim'), ('KAPORTA', 'Kaporta ve Boya'), ('LASTIK', 'Lastik ve Jant'), ('YEDEK', 'Yedek Parça'), ('EGZOZ', 'Egzoz ve Emisyon'), ('TORNACI', 'Torna ve Tesviye'), ('YOLYARDIM', 'Yol Yardım & Çekici'), ('EKSPERTIZ', 'Oto Ekspertiz'), ('DOSEME', 'Oto Döşeme & Kılıf')], max_length=50, verbose_name='Kategori'),
        ),
    ]
