# Generated by Django 5.2.8 on 2025-11-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0002_alter_dukkan_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukkan',
            name='bekleme_salonu',
            field=models.BooleanField(default=False, verbose_name='Bekleme Salonu Var'),
        ),
        migrations.AddField(
            model_name='dukkan',
            name='ikame_arac',
            field=models.BooleanField(default=False, verbose_name='İkame Araç Veriyor'),
        ),
        migrations.AddField(
            model_name='dukkan',
            name='kredi_karti',
            field=models.BooleanField(default=False, verbose_name='Kredi Kartı Geçerli'),
        ),
        migrations.AddField(
            model_name='dukkan',
            name='nobetci',
            field=models.BooleanField(default=False, verbose_name='7/24 Açık / Nöbetçi'),
        ),
    ]
