# Generated by Django 5.2.8 on 2025-11-24 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0003_dukkan_bekleme_salonu_dukkan_ikame_arac_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('metin', models.TextField(verbose_name='Yorumunuz')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('dukkan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='rehber.dukkan')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
    ]
