# Generated by Django 5.2.8 on 2025-11-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0004_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukkan',
            name='goruntulenme',
            field=models.IntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
    ]
