# Generated by Django 5.2.8 on 2025-11-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0005_dukkan_goruntulenme'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukkan',
            name='yayinda',
            field=models.BooleanField(default=False, verbose_name='Yayında mı? (Onay)'),
        ),
    ]
