# Generated by Django 5.2.8 on 2025-11-25 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0006_dukkan_yayinda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_model', models.CharField(max_length=100, verbose_name='Marka & Model')),
                ('yil', models.IntegerField(default=2015, verbose_name='Model Yılı')),
                ('km', models.IntegerField(verbose_name='Güncel Kilometre')),
                ('son_bakim_km', models.IntegerField(blank=True, null=True, verbose_name='Son Bakım KM')),
                ('yakit', models.CharField(choices=[('dizel', 'Dizel'), ('benzin', 'Benzin/LPG'), ('elektrik', 'Elektrik')], default='dizel', max_length=20)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
