# Generated by Django 5.2.8 on 2025-11-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0008_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukkan',
            name='hizmet_sinifi',
            field=models.CharField(choices=[('EKONOMIK', 'Ekonomik - Bütçe Dostu'), ('STANDART', 'Standart - Fiyat/Performans'), ('PREMIUM', 'Premium - Orijinal Parça & Yetkili Kalitesi')], default='STANDART', max_length=20, verbose_name='Hizmet Sınıfı'),
        ),
        migrations.AddField(
            model_name='dukkan',
            name='kampanya_baslik',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kampanya Başlığı (Örn: Kış İndirimi)'),
        ),
        migrations.AddField(
            model_name='dukkan',
            name='kampanya_detay',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kampanya Detayı (Örn: Tüm akülerde %20 indirim)'),
        ),
        migrations.AlterField(
            model_name='dukkan',
            name='kategori',
            field=models.CharField(choices=[('MOTOR', 'Motor ve Mekanik'), ('BAKIM', 'Periyodik Bakım & Yağ'), ('ELEKTRIK', 'Oto Elektrik ve Beyin'), ('AKU', 'Akü Satış & Değişim'), ('KAPORTA', 'Kaporta ve Boya'), ('LASTIK', 'Lastik ve Jant'), ('YEDEK', 'Yedek Parça'), ('EGZOZ', 'Egzoz ve Emisyon'), ('TORNACI', 'Torna ve Tesviye'), ('YOLYARDIM', 'Yol Yardım & Çekici'), ('EKSPERTIZ', 'Oto Ekspertiz'), ('DOSEME', 'Oto Döşeme & Kılıf'), ('KILIT', 'Oto Kilit & Anahtar')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='dukkan',
            name='konum_linki',
            field=models.URLField(blank=True, max_length=850, verbose_name='Google Harita Linki'),
        ),
    ]
