# Generated by Django 5.2.8 on 2025-12-03 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0009_dukkan_hizmet_sinifi_dukkan_kampanya_baslik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArizaTespitKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('marka_model', models.CharField(blank=True, max_length=100, verbose_name='Marka & Model')),
                ('yil', models.IntegerField(blank=True, null=True, verbose_name='Model Yılı')),
                ('km', models.IntegerField(blank=True, null=True, verbose_name='Kilometre')),
                ('yakit_tipi', models.CharField(blank=True, choices=[('dizel', 'Dizel'), ('benzin', 'Benzin/LPG'), ('elektrik', 'Elektrik')], max_length=20, verbose_name='Yakıt Tipi')),
                ('sikayet_metin', models.TextField(verbose_name='Şikayet / Açıklama')),
                ('belirtiler', models.JSONField(blank=True, default=list)),
                ('sonuc', models.JSONField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ariza_kayitlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
    ]
